# 使用语言
language: node_js
# node版本
node_js: 8
# 设置只监听哪个分支
branches:
  only:
  - source
# tarvis生命周期执行顺序详见官网文档
before_install:
- npm install -g hexo-cli
install:
# 不用yarn的话这里改成 npm i 即可
- yarn
script:
- gulp
after_success:
- cd ./public
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
# 这里的 REPO_TOKEN 即之前在 travis 项目的环境变量里添加的
- git push --quiet --force https://$TOKEN@github.com/lewis617/lewis617.github.io.git
  master