# Header
menu:
  主页: /
  归档: /archives
  关于我: /about

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- video
- series_posts
# - category
# - tag
- tagcloud
# - archive
- recent_posts
- links

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-88398388-1
gauges_analytics:
favicon: /css/images/favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:

donate:
  text: '如果您觉得本博客帮到了您，就打赏支持一下吧～'
  wechat: '/css/images/1556699647494-0.jpg'
  alipay: '/css/images/1556699647501-1.jpg'
